### ISSUE TITLE
dates for some plots not correct

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#62]
Should be like 2016-2019. I think this is based on the mechanism of the plot itself. I think it only happens when one plots multiple points at the same time in step 2. For a single plot it appears to work ok.

![image](https://user-images.githubusercontent.com/15234556/59443132-76a55380-8dc9-11e9-9f32-999bbfda2dd8.png)

**Comment by malonzo47** [comment]
May only happen when user manually enlarges window after plots are drawn.

**Comment by 0xF217** [comment]
I can't reproduce the issue. Please clarify the steps to reproduce.
What is the OBJECTID for these plots? Using the demo dataset, I have "20. Puragi village, land rights conflict" for OBJECTID 9.

**Comment by malonzo47** [comment]
Try objectids 1:8 (all at the same time). I just recreated like that for windows release 1.0.2. I did NOT have the problem for 1 only or 1:4.

**Comment by malonzo47** [comment]
Note, this issue also occurs when running source code via linux container

**Comment by FreelanceDev217** [comment]
Fixed. Please check and close.

**Comment by 0xF217** [comment]
Fixed. It should be fine on all kinds of installations.

**Comment by malonzo47** [comment]
This is still happening. I am running the Windows binary from develop.

**Comment by 0xF217** [comment]
All the latest work is done on master branch. Please check the latest binary [release](https://github.com/malonzo47/pynita_GUI/releases/tag/1.0.2)

**Comment by 0xF217** [comment]
Please check the new release [1.0.3](https://github.com/malonzo47/pynita_GUI/releases/tag/1.0.3).

**Comment by malonzo47** [comment]
Seems to work in new release.
