### ISSUE TITLE
recovery years not specified (metric image creation)

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#66]
The recovery image appears to have a hardcoded number of years. The user should be able to specify this number at the time of metric image generation. (Similar functionality to specification of custom value change)

**Comment by malonzo47** [comment]
The user should be able to specify a number of years over which to judge recovery of vegetation index value. 

This year value currently is hardcoded as "1" in pynita_gui_main in line 1071:
nita.MI_recovery(1, option='diff', plot=self.plot12.isChecked(), save=self.save12.isChecked(), fn='recovery.tif', title = title, label=label)

This value should, instead be updated by user from Step 4, #12 
Label in GUI (in blue text like "Start Date"): "Years:"

The same change should be made for Step 4, #13. (See pynita_gui_main line 1076).
Label in GUI (in blue text like "Start Date"): "Years:"

**Comment by 0xF217** [comment]
Fixed. Please check the master branch running from the source.

**Comment by malonzo47** [comment]
Seems to work. Two small changes: 
1) make text boxes for user data entry no larger than they need to be to fit, for example, yyyyddd; 
2) allow for multiple Recovery plots to be open at the same time. For instance, I should be able to run a 2 year recovery to create a plot labeled "Recovery 2" and then a 1 year recovery popping up "Recovery 1". (Multiple window functionality should be like "Value Change Custom" which currently allows for this and names them specifically)

**Comment by 0xF217** [comment]
Fixed. Please check the latest source at the master branch.

**Comment by malonzo47** [comment]
Number 1 is not fixed. The boxes are still the same size:
![image](https://user-images.githubusercontent.com/15234556/80633011-17beec00-8a26-11ea-99c9-439d87b567c3.png)

**Comment by malonzo47** [comment]
Number 2 looks good!

**Comment by 0xF217** [comment]
Fixed.

**Comment by malonzo47** [comment]
This is still not fixed for all three boxes. We're talking about Recovery here and neither of those have been updated:
![image](https://user-images.githubusercontent.com/15234556/80718698-7a68c400-8ac8-11ea-9b43-2afb7ceead87.png)

**Comment by 0xF217** [comment]
Well, because we can have several year values in Recovery and Recover CMP, I think it's hard to set the limit of the width of these two textboxes. Please let me know your thought. How many characters shall we limit the inputs?

**Comment by malonzo47** [comment]
Never needs more than 3 characters. Thanks!

**Comment by 0xF217** [comment]
Fixed.

**Comment by malonzo47** [comment]
Looks good.
